# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_Pierre_number:
    path: /pierre/number
    controller: App\Controller\PierreController::number
    
Form_Experience:
    path: /Experience/create
    controller: App\Controller\ExperienceController::create