# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

index:
    path: /pierre/number
    controller: App\Controller\PierreController::number
    
Form_experience:
    path: /Experience/create
    controller: App\Controller\ExperienceController::create
    
valid_experience:
    path: /Experience/valid
    controller: App\Controller\ExperienceController::valid
    
Form_formations:
    path: /Formations/create
    controller: App\Controller\ExperienceController::create
    
valid_formations:
    path: /Formations/valid
    controller: App\Controller\FormationsController::valid
    
